language: node_js
sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
node_js:
- '6'
#- '5'
#- '4'
- xvfb-run npm test
- polymer build --bundle --js-minify --css-minify --html-minify
after_success:
- ./travis_scripts/deploy.sh
 notifications:
    slack: wisebird-application:QTYLKZbxCxmRKti24F9fo9BF