sudo: required
dist: trusty
addons:
  firefox: 'latest'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "node"
  - "6"
before_script:
  - "npm install -g bower polymer-cli@next"
  - "bower install"
script:
  - xvfb-run npm test
  - xvfb-run npm run test:integration
notifications:
  email: false
  slack: "wisebird-application:QTYLKZbxCxmRKti24F9fo9BF"