language: node_js
sudo: required
dist: trusty
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
node_js:
- '6'
#- '5'
#- '4'
before_script:
- npm install -g bower polymer-cli
- bower install
script:
- npm run lint
- polymer build --bundle --js-minify --css-minify --html-minify
notifications:
  email: false
  slack: "wisebird-application:QTYLKZbxCxmRKti24F9fo9BF"